//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meal
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> discount_price { get; set; }
        public string picture { get; set; }
        public string discription { get; set; }
        public int category_id { get; set; }
    
        public virtual categories categories { get; set; }
    }
}
